// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAPyIsvX5eIFExKATdEdVzW2uFIbIdtXc',
    appId: '1:218788584136:web:934fac1aa944eb2dc2e3fd',
    messagingSenderId: '218788584136',
    projectId: 'tasks-management-team10-140126',
    authDomain: 'tasks-management-team10-140126.firebaseapp.com',
    storageBucket: 'tasks-management-team10-140126.firebasestorage.app',
    measurementId: 'G-8TFJP1JQS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwYDb10cyfyrmpZcqUjP3HRqNMHDn0rqg',
    appId: '1:218788584136:android:db3eb676bd9768e5c2e3fd',
    messagingSenderId: '218788584136',
    projectId: 'tasks-management-team10-140126',
    storageBucket: 'tasks-management-team10-140126.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMp0HvM1FaZFH4g1sDG0n0Su8BsJW5TU',
    appId: '1:218788584136:ios:b0a27bcbe7bf847ec2e3fd',
    messagingSenderId: '218788584136',
    projectId: 'tasks-management-team10-140126',
    storageBucket: 'tasks-management-team10-140126.firebasestorage.app',
    iosBundleId: 'com.example.flutterManageTeamTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrMp0HvM1FaZFH4g1sDG0n0Su8BsJW5TU',
    appId: '1:218788584136:ios:b0a27bcbe7bf847ec2e3fd',
    messagingSenderId: '218788584136',
    projectId: 'tasks-management-team10-140126',
    storageBucket: 'tasks-management-team10-140126.firebasestorage.app',
    iosBundleId: 'com.example.flutterManageTeamTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAPyIsvX5eIFExKATdEdVzW2uFIbIdtXc',
    appId: '1:218788584136:web:d186a4d310ac85f5c2e3fd',
    messagingSenderId: '218788584136',
    projectId: 'tasks-management-team10-140126',
    authDomain: 'tasks-management-team10-140126.firebaseapp.com',
    storageBucket: 'tasks-management-team10-140126.firebasestorage.app',
    measurementId: 'G-41XJ4ZKYGH',
  );
}
